### ISSUE TITLE
blocklist.lsrules is too big

### ISSUE THREAD

**Issue by 357r4bd** [balupton/littlesnitch-filters#1]
Little Snitch is telling me blocklist.lsrules is too big (greater than 10,000 entries).

**Comment by balupton** [comment]
Yeah. I emailed them, they said they are looking at solving it in a future release, and that the reason it is disabled is because of current performance issues. You should be able to download it and import it locally though, rather rhan as a subscription.

Because of the above, for I ended up skipping the littlesnirch blocklist and using a hosts file blocklist instead. There are numerous ones on github available.

**Comment by balupton** [comment]
I've decided that the hosts file solution is better for large blocklists, so will be making the little snitch blocklist much more minimal (for things that I find excluded for the hosts file ones).

Here is the command I did up for selecting a hosts file:

https://github.com/balupton/dotfiles/blob/master/.scripts/commands/select-hosts
